services:
  - type: web
    name: formularios
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn taller_formularios.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: taller_formularios.settings
      - key: PYTHON_VERSION
        value: 3.12.3
