# Generated by Django 5.2.6 on 2025-09-25 16:30

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del registro', primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(db_index=True, help_text='Nombre completo de la persona', max_length=150, verbose_name='Nombre Completo')),
                ('documento_identidad', models.CharField(db_index=True, help_text='Número de documento de identidad', max_length=20, verbose_name='Documento de Identidad')),
                ('correo_electronico', models.EmailField(help_text='Dirección de correo electrónico válida', max_length=254, verbose_name='Correo Electrónico')),
                ('fecha_asistencia', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Fecha del registro de asistencia', verbose_name='Fecha de Asistencia')),
                ('hora_ingreso', models.TimeField(help_text='Hora de entrada', verbose_name='Hora de Ingreso')),
                ('hora_salida', models.TimeField(help_text='Hora de salida', verbose_name='Hora de Salida')),
                ('presente', models.BooleanField(default=True, help_text='Indica si la persona estuvo presente', verbose_name='Presente')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales (opcional)', max_length=500, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha_asistencia', '-hora_ingreso'],
                'indexes': [models.Index(fields=['fecha_asistencia', 'presente'], name='asistencia__fecha_a_d8d967_idx'), models.Index(fields=['documento_identidad'], name='asistencia__documen_5a4447_idx'), models.Index(fields=['fecha_creacion'], name='asistencia__fecha_c_f575c4_idx')],
                'unique_together': {('documento_identidad', 'fecha_asistencia')},
            },
        ),
    ]
