# Generated by Django 5.2.5 on 2025-10-23 21:37

import django.core.validators
import solicitudes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(help_text='Ingrese el nombre completo', max_length=150, verbose_name='Nombre completo del solicitante')),
                ('documento_identidad', models.CharField(help_text='Ingrese solo números', max_length=20, validators=[django.core.validators.RegexValidator(message='El documento de identidad debe contener solo números.', regex='^\\d+$')], verbose_name='Documento de identidad')),
                ('correo_electronico', models.EmailField(help_text='Ingrese un correo electrónico válido', max_length=254, verbose_name='Correo electrónico')),
                ('telefono_contacto', models.CharField(help_text='Ingrese solo números (7-15 dígitos)', max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener entre 7 y 15 números.', regex='^\\d{7,15}$')], verbose_name='Teléfono de contacto')),
                ('tipo_solicitud', models.CharField(choices=[('academica', 'Académica'), ('administrativa', 'Administrativa'), ('tecnica', 'Técnica'), ('otra', 'Otra')], help_text='Seleccione el tipo de solicitud', max_length=20, verbose_name='Tipo de solicitud')),
                ('asunto', models.CharField(help_text='Resuma brevemente el asunto de su solicitud', max_length=200, verbose_name='Asunto')),
                ('descripcion_detallada', models.TextField(help_text='Proporcione una descripción completa de su solicitud', verbose_name='Descripción detallada')),
                ('fecha_solicitud', models.DateField(auto_now_add=True, help_text='Fecha en que se realiza la solicitud', verbose_name='Fecha de solicitud')),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Archivo opcional (máximo 5MB)', null=True, upload_to=solicitudes.models.upload_to_solicitudes, validators=[solicitudes.models.validar_tamaño_archivo], verbose_name='Archivo adjunto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
